###############################################################################
#   @author         :   Trent Stanton
#   @date           :   24/02/2018
#   @package        :   Battery Levels
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:
    sensor.battery_backdoor_sensor:
      icon: mdi:car-battery
    sensor.battery_frontdoor_sensor:
      icon: mdi:car-battery
    sensor.battery_bedroomwindow_sensor:
      icon: mdi:car-battery
    sensor.battery_livingroomwindow1_sensor:
      icon: mdi:car-battery
    sensor.battery_livingroomwindow2_sensor:
      icon: mdi:car-battery
    sensor.battery_livingroomwindow3_sensor:
      icon: mdi:car-battery
    sensor.battery_washingmachine_sensor:
      icon: mdi:car-battery
    sensor.battery_hallway_sensor:
      icon: mdi:car-battery
    sensor.battery_spareswitch_sensor:
      icon: mdi:car-battery
    sensor.battery_bedroomswitch_sensor:
      icon: mdi:car-battery
    sensor.battery_entryswitch_sensor:
      icon: mdi:car-battery
    sensor.battery_bedroomtemp_sensor:
      icon: mdi:car-battery
    sensor.battery_livingroommulti_sensor:
      icon: mdi:car-battery
    sensor.battery_smartlock:
      icon: mdi:car-battery

group:
  Battery Levels:
    control: hidden
    entities:
      - sensor.battery_backdoor_sensor
      - sensor.battery_frontdoor_sensor
      - sensor.battery_bedroomwindow_sensor
      - sensor.battery_livingroomwindow1_sensor
      - sensor.battery_livingroomwindow2_sensor
      - sensor.battery_livingroomwindow3_sensor
      - sensor.battery_washingmachine_sensor
      - sensor.battery_hallway_sensor
      - sensor.battery_spareswitch_sensor
      - sensor.battery_bedroomswitch_sensor
      - sensor.battery_entryswitch_sensor
      - sensor.battery_bedroomtemp_sensor
      - sensor.battery_livingroommulti_sensor
      - sensor.battery_smartlock

sensor:
  - platform: template
    sensors:
      battery_backdoor_sensor:
        value_template: '{% if states.binary_sensor.door_window_sensor_158d000186f0ec is not none %}
          {{ states.binary_sensor.door_window_sensor_158d000186f0ec.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Back Door Sensor Battery'
      battery_frontdoor_sensor:
        value_template: '{% if states.binary_sensor.door_window_sensor_158d00019f3211 is not none %}
          {{ states.binary_sensor.door_window_sensor_158d00019f3211.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Front Door Sensor Battery'
      battery_bedroomwindow_sensor:
        value_template: '{% if states.binary_sensor.door_window_sensor_158d0001d7acfc is not none %}
          {{ states.binary_sensor.door_window_sensor_158d0001d7acfc.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Bedroom Window Sensor Battery'
      battery_livingroomwindow1_sensor:
        value_template: '{% if states.binary_sensor.door_window_sensor_158d0001e037dc is not none %}
          {{ states.binary_sensor.door_window_sensor_158d0001e037dc.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Living Room Window 1 Sensor Battery'
      battery_livingroomwindow2_sensor:
        value_template: '{% if states.door_window_sensor_158d00019fbe38 is not none %}
          {{ states.binary_sensor.door_window_sensor_158d00019fbe38.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Living Room Window 2 Sensor Battery'
      battery_livingroomwindow3_sensor:
        value_template: '{% if states.binary_sensor.door_window_sensor_158d0001a4a872 is not none %}
          {{ states.binary_sensor.door_window_sensor_158d0001a4a872.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Living Room Window 3 Sensor Battery'
      battery_washingmachine_sensor:
        value_template: '{% if states.binary_sensor.door_window_sensor_158d00019f886a is not none %}
          {{ states.binary_sensor.door_window_sensor_158d00019f886a.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Washing Machine Sensor Battery'
      battery_hallway_sensor:
        value_template: '{% if states.binary_sensor.motion_sensor_158d000165627b is not none %}
          {{ states.binary_sensor.motion_sensor_158d000165627b.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Hallway Sensor Battery'
      battery_spareswitch_sensor:
        value_template: '{% if states.binary_sensor.switch_158d00016449a2 is not none %}
          {{ states.binary_sensor.switch_158d00016449a2.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Spare Switch Sensor Battery'
      battery_bedroomswitch_sensor:
        value_template: '{% if states.binary_sensor.switch_158d0001a21086 is not none %}
          {{ states.binary_sensor.switch_158d0001a21086.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Bedroom Switch Sensor Battery'
      battery_entryswitch_sensor:
        value_template: '{% if states.binary_sensor.wall_switch_both_158d000170ef78 is not none %}
          {{ states.binary_sensor.wall_switch_both_158d000170ef78.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Entry Switch Sensor Battery'
      battery_bedroomtemp_sensor:
        value_template: '{% if states.sensor.humidity_158d0001a2e878 is not none %}
          {{ states.sensor.humidity_158d0001a2e878.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Bedroom Temp Sensor Battery'
      battery_livingroommulti_sensor:
        value_template: '{% if states.zwave.fibaro_system_fgms001zw5_motion_sensor is not none %}
          {{ states.zwave.fibaro_system_fgms001zw5_motion_sensor.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Living Room Multi Sensor Battery'
      battery_smartlock:
        value_template: '{% if states.zwave.kas600_zwave_lock is not none %}
          {{ states.zwave.kas600_zwave_lock.attributes.battery_level }}
          {% else %}
            n/a
          {% endif %}'
        unit_of_measurement: '%'
        friendly_name: 'Smart Lock Battery'

# Need to add: Unnamed Switches and Motion Sensors